export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';